language: "en-US"
early_access: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  auto_review:
    enabled: true

chat:
  auto_reply: true

path_filters:
  - "!dist/**"
  - "!**/*.lock"

path_instructions:
  - path: "src/main/java/com/abaco/loans/controller/**"
    instructions: |
      SECURITY: Verify JWT signature validation is enforced on secured endpoints.
      COMPLIANCE: Ensure logging excludes 'password', 'token', 'cvv', and any other PII.
      CRITICAL: For any payment-related endpoints, verify idempotency keys are checked before processing. This is a critical step to prevent CSRF attacks.